baseURL = "https://www.christianreddington.co.uk/"
languageCode = "en-gb"
title = "Christian Reddington"
theme = "goa"

[[menu.main]]
    name = "Cloud with Chris (Podcast)"
    weight = 200
    url = "https://www.cloudwithchris.com"
[[menu.main]]
    name = "blog"
    weight = 200
    url = "/blog/"
[[menu.main]]
    name = "about"
    weight = 200
    url = "/about/"

[params.extra]
    copyright = "© 2020. Chris Reddington. [Some Rights Reserved](https://creativecommons.org/licenses/by/3.0/)."

[params.social]
    github = "chrisreddington"
    linkedin = "chrisreddington"
    twitter = "reddobowen"

[params]
    author = "Chris Reddington"
    intro = "Welsh Tech Geek, Cloud Advocate, Musical Theatre Enthusiast and Improving Improviser!"
    description = "Please feel free to connect with / follow me on the below platforms. I'd also love if you could follow my podcast on any platform of your choice, and the associated social media channels too!"
    authorimage = "chris-headshot.jpg"
    dateformat = "Mon 2 Jan, 2006"

[markup.goldmark.renderer]
    unsafe= true
