baseURL = "https://www.christianreddington.co.uk/"
languageCode = "en-gb"
title = "Christian Reddington"
theme = "goa"

[[menu.main]]
    name = "blog"
    weight = 100
    url = "/blog/"
[[menu.main]]
    name = "about"
    weight = 200
    url = "/about/"

[params.extra]
    copyright = "© 2020. Chris Reddington. [Some Rights Reserved](https://creativecommons.org/licenses/by/3.0/)."

[params.social]
    github = "christianreddington"
    linkedin = "christianreddington"
    twitter = "reddobowen"

[params]
    author = "Chris Reddington"
    intro = "Welsh Tech Geek, Azure Advocate and Musical Theatre Enthusiast!"
    description = "Please feel free to connect with / follow me on the below platforms, and also take a look through any of my updates below!"
    authorimage = "chris-headshot.jpg"
    dateformat = "Mon 2 Jan, 2006"

[markup.goldmark.renderer]
    unsafe= true